version: '3.3'
services:
    dockvine:
        environment:
            mysql: dockvine_env_mysql_1
            redis: dockvine_env_redis_1
            APP_ENV: local
        volumes:
            - './log:/var/log/'
            - './dockvine_api:/var/www/dockvine/dockvine_api'
            - './wix:/var/www/dockvine/wix'
            - './storage:/var/www/dockvine/dockvine_api/app/storage'
        ports:
            - 80:80
            - 443:443
        container_name: dockvine
        image: dockvine
        networks:
           - default
    mysql:
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - '/home/ec2-user/dockvine/dockvine_env/mysql:/var/lib/mysql'
        image: mysql:5.7
        command: --skip-grant-tables
        networks:
           - default
    redis:
        image: redis
        networks:
           - default

