FROM node:10-alpine AS build
COPY .  /var/www/dockvine/
WORKDIR /var/www/dockvine/dockvine_toolbar
RUN sh build.sh

FROM php:5-apache-jessie
RUN curl -s https://getcomposer.org/installer | php
COPY --from=build /var/www/dockvine /var/www/dockvine
COPY dockvine_env/sites-enabled /etc/apache2/sites-enabled
